import { positional, promptFrom, required, integer, usage } from "../args.mjs";
import { writeFile } from "node:fs/promises";
import { spec, reviewSpec, recipient } from "../spec.mjs";
import { RpcError } from "../rpc.mjs";

const mutation = (method, params, key) => ({ method, params, mutation: true, key });
const read = (method, params) => ({ method, params });
async function send(ctx) { const { positionals, options, rpc } = ctx; const projectId = required(options, "project"); let workflowId = options.get("workflow"); if (typeof workflowId !== "string" || !workflowId) { const projects = await rpc("projects.list", {}); const project = (projects.items ?? projects).find?.((item) => item.id === projectId); throw usage(`Missing required --workflow; workflows for ${projectId}: ${project ? project.workflows.map((item) => item.id).join(", ") : "(unknown project)"}`); } const prompt = await promptFrom(positionals, 1); const to = recipient(options, true, true); return mutation(options.has("new-room") ? "rooms.create" : "rooms.open", { title: options.get("title") || prompt.slice(0, 80), projectId, workflowId, prompt, ...(to === null ? {} : { recipients: to === "both" ? ["claude", "codex"] : [to] }), ...await spec(options), ...reviewSpec(options), ...(typeof options.get("session") === "string" ? { sessionId: options.get("session") } : {}), ...(options.has("force") ? { force: true } : {}) }); }
async function followup(ctx) { const { positionals, options, rpc } = ctx; const roomId = positional(positionals, 1, "Room ID"); if (!options.has("from-review")) return mutation("messages.create", { roomId, body: await promptFrom(positionals, 2), recipient: recipient(options), ...await spec(options), ...reviewSpec(options) }); if (positionals.length > 2) throw usage("--from-review does not accept an additional prompt"); const detail = await rpc("rooms.get", { roomId }); const candidates = (detail.jobs ?? []).filter((job) => job.role === "work" && (job.review?.verdict === "refuted" || job.reviewOutcome === "refuted")); if (!candidates.length) throw usage(`No refuted work job found in room ${roomId}`); const timestamp = (job) => Date.parse(job.createdAt ?? job.review?.createdAt ?? "") || 0; const job = candidates.reduce((newest, candidate) => timestamp(candidate) > timestamp(newest) ? candidate : newest); return mutation("messages.create", { roomId, body: `REFUTER VERDICT:\n${job.gradeNote ?? ""}\nAddress exactly this, nothing else. No formatter. Every changed line traces to the verdict.`, recipient: job.provider, ...await spec(options), ...reviewSpec(options) }); }
async function wait(ctx) { const jobId = positional(ctx.positionals, 1, "Job ID"), timeout = ctx.options.has("timeout") ? integer(required(ctx.options, "timeout"), "--timeout", { min: 1, max: 86_400 }) : 540, deadline = Date.now() + timeout * 1000; for (;;) { const result = await ctx.rpc("jobs.get", { jobId }); if (["succeeded", "failed", "cancelled"].includes(result.state)) return { result, negative: result.state !== "succeeded" }; if (Date.now() >= deadline) throw new RpcError("TRANSPORT", `Timed out waiting for ${jobId} (state ${result.state})`); await new Promise((resolve) => setTimeout(resolve, 2000)); } }
async function acceptance(ctx, verdict) { const jobId = positional(ctx.positionals, 1, "Job ID"); const check = await ctx.rpc("jobs.acceptance.check", { jobId }); const evaluation = check.evaluation ?? {}; const criteria = evaluation.criteria ?? []; let checked = []; const raw = ctx.options.get("criteria"); if (typeof raw === "string") checked = raw.split(",").filter(Boolean).map((value) => integer(value, "--criteria", { min: 0, max: criteria.length - 1 })); if (new Set(checked).size !== checked.length) throw usage("--criteria must contain distinct indexes"); if (ctx.options.has("yes") && !raw && !process.stdin.isTTY) throw usage("--yes requires --criteria when stdin is not a TTY"); if (verdict === "accepted" && checked.length !== criteria.length) throw usage("Accepted verdict requires every --criteria index"); const note = typeof ctx.options.get("note") === "string" ? ctx.options.get("note") : await promptFrom(ctx.positionals, 2); if (!note) throw usage("Acceptance note is required"); const explicitFingerprint = ctx.options.get("fingerprint"), explicitEvidenceHash = ctx.options.get("evidence-hash"); if (explicitFingerprint !== undefined && explicitFingerprint !== evaluation.fingerprint) throw usage("--fingerprint must match the acceptance check"); if (explicitEvidenceHash !== undefined && explicitEvidenceHash !== evaluation.evidenceHash) throw usage("--evidence-hash must match the acceptance check"); const fingerprint = evaluation.fingerprint, evidenceHash = evaluation.evidenceHash; if (typeof fingerprint !== "string" || typeof evidenceHash !== "string") throw usage("Acceptance check did not provide fingerprint and evidence hash"); const routingGrade = ctx.options.get("grade"); if (routingGrade !== undefined && !["good", "bad"].includes(routingGrade)) throw usage("--grade must be good or bad"); return mutation("jobs.acceptance.record", { jobId, verdict, note, checked, fingerprint, evidenceHash, ...(routingGrade ? { routingGrade } : {}) }); }
async function evidence(ctx) { const jobId = positional(ctx.positionals, 1, "Job ID"); const job = await ctx.rpc("jobs.get", { jobId }); let cursor; const pages = []; do { const page = await ctx.rpc("jobs.evidence", { roomId: job.roomId, jobId, ...(cursor ? { cursor } : {}) }); pages.push(page); cursor = page.nextCursor; } while (cursor); const artifact = pages.flatMap((page) => page.artifacts ?? []).find((item) => item.kind === "evidence"); let content = null; if (artifact) { const chunks = []; let offset = 0; do { const chunk = await ctx.rpc("artifacts.read", { id: artifact.id, offset }); chunks.push(Buffer.from(chunk.data, "base64")); offset = chunk.nextOffset; } while (offset !== null); content = Buffer.concat(chunks); if (ctx.options.has("out")) await writeFile(required(ctx.options, "out"), content); } else if (ctx.options.has("out")) throw usage("No evidence artifact is available for this job"); return { result: { pages, ...(content ? { artifact: { id: artifact.id, bytes: content.length, text: content.toString("utf8") } } : {}) } }; }
async function diff(ctx) { const output = await evidence(ctx); const changes = output.result.pages.flatMap((page) => page.changes ?? []); return { result: ctx.options.has("stat") ? changes.map((change) => ({ path: change.path, additions: change.additions, deletions: change.deletions })) : changes }; }
export const jobs = [
  { names: ["send"], usage: "send PROMPT --project ID --workflow ID [spec]", summary: "start or join a room", run: send },
  { names: ["followup"], usage: "followup ROOM MESSAGE --to claude|codex", summary: "continue a room", run: followup },
  { names: ["handoff"], usage: "handoff ROOM --from JOB --to claude|codex [MESSAGE]", summary: "create a handoff", run: async (c) => mutation("handoffs.create", { roomId: positional(c.positionals, 1, "Room ID"), sourceJobId: required(c.options, "from"), targetProvider: recipient(c.options, false), instruction: c.positionals.slice(2).join(" ").trim() || "Review the selected agent result.", ...await spec(c.options), ...reviewSpec(c.options) }) },
  { names: ["cancel", "retry"], usage: "cancel|retry JOB", summary: "cancel or retry a job", run: async (c) => { const command = c.positionals[0]; return mutation(`jobs.${command}`, { jobId: positional(c.positionals, 1, "Job ID"), ...(command === "retry" && typeof c.options.get("tier") === "string" ? { tier: c.options.get("tier") } : {}), ...(command === "retry" ? reviewSpec(c.options) : {}) }); } },
  { names: ["review"], usage: "review JOB [--to PROVIDER --tier TIER]", summary: "request manual review", run: async (c) => mutation("jobs.review", { jobId: positional(c.positionals, 1, "Job ID"), ...(c.options.has("to") ? { provider: recipient(c.options, false) } : {}), ...(typeof c.options.get("tier") === "string" ? { tier: c.options.get("tier") } : {}), ...reviewSpec(c.options) }) },
  { names: ["wait"], usage: "wait JOB [--timeout SECS]", summary: "wait for successful job", run: wait },
  { names: ["acceptance-check"], usage: "acceptance-check JOB", summary: "check current acceptance", run: async (c) => { const result = await c.rpc("jobs.acceptance.check", { jobId: positional(c.positionals, 1, "Job ID") }); return { result, negative: !result.accepted }; } },
  { names: ["accept"], usage: "accept JOB --criteria 0,1 --note TEXT", summary: "record human acceptance", run: (c) => acceptance(c, "accepted") },
  { names: ["reject"], usage: "reject JOB --note TEXT [--criteria N]", summary: "record human rejection", run: (c) => acceptance(c, "rejected") },
  { names: ["grade"], usage: "grade JOB good|bad [--note TEXT]", summary: "submit advisory grade", run: async (c) => mutation("jobs.grade", { jobId: positional(c.positionals, 1, "Job ID"), grade: positional(c.positionals, 2, "Grade good|bad"), note: c.options.get("note") ?? c.positionals[3] ?? null }) },
  { names: ["logs", "result"], usage: "logs|result JOB", summary: "read job output", run: async (c) => read(`jobs.${c.positionals[0]}`, { jobId: positional(c.positionals, 1, "Job ID") }) },
  { names: ["evidence"], usage: "evidence JOB", summary: "read paged evidence", run: evidence },
  { names: ["diff"], usage: "diff JOB [--stat]", summary: "show job changes", run: diff },
  { names: ["rollouts"], usage: "rollouts JOB", summary: "show rollout group", run: async (c) => read("rollouts.get", { jobId: positional(c.positionals, 1, "Job ID") }) },
];
