import { readFile } from "node:fs/promises";
import { integer, positional, promptFrom, required, usage } from "../args.mjs";
import { formatStatus } from "../format.mjs";
const mutation = (method, params) => ({ method, params, mutation: true });
export const rooms = [
  { names: ["record"], usage: "record ROOM MESSAGE --author human|claude|codex", summary: "record a turn", run: async (c) => { const author = c.options.get("author"); if (!["human", "claude", "codex"].includes(author)) throw usage("--author must be human, claude or codex"); const fresh = c.options.has("title"); const body = typeof c.options.get("file") === "string" ? (await readFile(c.options.get("file"), "utf8")).trim() : await promptFrom(c.positionals, fresh ? 1 : 2); const params = { author, body }; if (fresh) Object.assign(params, { title: required(c.options, "title"), projectId: required(c.options, "project"), workflowId: required(c.options, "workflow") }); else params.roomId = positional(c.positionals, 1, "Room ID"); for (const key of ["model", "effort"]) if (typeof c.options.get(key) === "string") params[key] = c.options.get(key); return mutation("turns.record", params); } },
  { names: ["pin", "unpin", "archive", "unarchive"], usage: "pin|unpin|archive|unarchive ROOM", summary: "change room view state", run: async (c) => { const action = c.positionals[0]; return mutation(action.includes("pin") ? "rooms.pin" : "rooms.archive", { roomId: positional(c.positionals, 1, "Room ID"), value: !action.startsWith("un") }); } },
  { names: ["status"], usage: "status ROOM", summary: "show a room", run: async (c) => { const result = await c.rpc("rooms.get", { roomId: positional(c.positionals, 1, "Room ID") }); return c.options.has("json") ? { result } : { text: formatStatus(result) }; } },
  { names: ["ls"], usage: "ls [rooms|jobs] [filters]", summary: "list rooms or jobs", run: async (c) => { const roomsMode = c.positionals[1] === "rooms", limit = c.options.has("limit") ? integer(required(c.options, "limit"), "--limit", { min: 1, max: 200 }) : 50; return { method: `${roomsMode ? "rooms" : "jobs"}.list`, params: { limit, cursor: c.options.get("cursor") ?? null, ...(roomsMode ? { status: c.options.get("status") ?? null, ...(typeof c.options.get("session") === "string" ? { sessionId: c.options.get("session") } : {}) } : { state: c.options.get("state") ?? null }) } }; } },
  { names: ["sessions"], usage: "sessions [new TITLE --project ID --workflow ID]", summary: "list or create sessions", run: async (c) => c.positionals[1] === "new" ? mutation("sessions.create", { title: positional(c.positionals, 2, "Session title"), projectId: required(c.options, "project"), workflowId: required(c.options, "workflow") }) : ({ method: "sessions.list", params: typeof c.options.get("project") === "string" ? { projectId: c.options.get("project") } : {} }) },
];
