import path from "node:path";
import { integer, positional, promptFrom, required, usage } from "../args.mjs";
export const tasks = [
  { names: ["inbox"], usage: "inbox", summary: "list pending tasks", run: async () => ({ method: "tasks.pending", params: {} }) },
  { names: ["tasks"], usage: "tasks ROOM", summary: "list room tasks", run: async (c) => ({ method: "tasks.list", params: { roomId: positional(c.positionals, 1, "Room ID") } }) },
  { names: ["task", "resume", "cancel-task", "checkpoint", "ack"], usage: "task|resume|cancel-task TASK", summary: "inspect or control a task", run: async (c) => { const name = c.positionals[0], taskId = positional(c.positionals, 1, "Task ID"); const method = { task: "tasks.get", resume: "tasks.resume", "cancel-task": "tasks.cancel", checkpoint: "tasks.checkpoint", ack: "tasks.controls.ack" }[name]; const params = { taskId }; if (name === "resume" && (c.options.has("cwd") || c.options.has("expected-fingerprint"))) { params.cwd = path.resolve(required(c.options, "cwd")); params.expectedFingerprint = required(c.options, "expected-fingerprint"); if (!/^[a-f0-9]{64}$/.test(params.expectedFingerprint)) throw usage("--expected-fingerprint must be a 64-character lowercase hexadecimal fingerprint"); } if (["checkpoint", "ack"].includes(name)) params.jobId = required(c.options, "job"); if (name === "ack") { params.controlIds = c.positionals.slice(2); if (!params.controlIds.length) throw usage("At least one control ID is required"); } return { method, params, mutation: name !== "task" }; } },
  { names: ["control"], usage: "control TASK instruction|decision|pause|resume MESSAGE", summary: "record task control", run: async (c) => { const kind = c.positionals[2]; if (!["instruction", "decision", "pause", "resume"].includes(kind)) throw usage("Control kind must be instruction, decision, pause, or resume"); return { method: "tasks.controls.create", params: { taskId: positional(c.positionals, 1, "Task ID"), kind, body: await promptFrom(c.positionals, 3) }, mutation: true, notice: "Control delivery and acknowledgement are separate; use checkpoint and ack to record receipt." }; } },
  { names: ["wait-task"], usage: "wait-task TASK [--timeout SECS]", summary: "wait for task completion", run: async (c) => { const taskId = positional(c.positionals, 1, "Task ID"), deadline = Date.now() + integer(c.options.get("timeout") ?? 540, "--timeout") * 1000; for (;;) { const result = await c.rpc("tasks.get", { taskId }); if (result.task.state !== "working") return { result, negative: result.task.state !== "completed" }; if (Date.now() >= deadline) throw usage(`Timed out waiting for ${taskId}`); await new Promise((resolve) => setTimeout(resolve, 2000)); } } },
];
