import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { promisify } from "node:util";

const exec = promisify(execFile);
const cli = path.resolve("bin/dovsky");
async function fixture(context, handler = () => ({})) {
  const root = await mkdtemp(path.join(os.tmpdir(), "w2-cli-"));
  const socketPath = path.join(root, "bus.sock"), calls = [];
  const server = createServer((socket) => { let body = ""; socket.setEncoding("utf8"); socket.on("data", (chunk) => { body += chunk; }); socket.on("end", () => { const request = JSON.parse(body); calls.push(request); const reply = handler(request, calls); socket.end(`${JSON.stringify(reply?.__rpc ? reply.value : { id: request.id, ok: true, result: reply ?? {} })}\n`); }); });
  await new Promise((resolve, reject) => { server.once("error", reject); server.listen(socketPath, resolve); });
  context.after(() => server.close());
  return { socketPath, calls, root };
}
const run = (args, socketPath, options = {}) => exec(cli, [...args, "--socket", socketPath, "--json"], options);
const rejected = (promise, pattern) => assert.rejects(promise, (error) => error.code === 2 && (!pattern || pattern.test(error.stderr)));

test("legacy 01 send retains narrow room-open request", async (context) => { const f = await fixture(context, () => ({ roomId: "r" })); await run(["send", "Audit this", "--project", "p", "--workflow", "w", "--to", "both", "--key", "k"], f.socketPath); assert.equal(f.calls[0].method, "rooms.open"); assert.equal(f.calls[0].idempotencyKey, "k"); assert.deepEqual(f.calls[0].params.recipients, ["claude", "codex"]); });
test("legacy 02 send new-room and session remain explicit", async (context) => { const f = await fixture(context, () => ({})); await run(["send", "x", "--project", "p", "--workflow", "w", "--new-room", "--session", "s"], f.socketPath); assert.equal(f.calls[0].method, "rooms.create"); assert.equal(f.calls[0].params.sessionId, "s"); });
test("legacy 03 sessions list preserves optional project", async (context) => { const f = await fixture(context); await run(["sessions", "--project", "p"], f.socketPath); assert.equal(f.calls[0].method, "sessions.list"); assert.deepEqual(f.calls[0].params, { projectId: "p" }); });
test("legacy 04 sessions new validates title locally", async (context) => { const f = await fixture(context); await run(["sessions", "new", "Ship", "--project", "p", "--workflow", "w"], f.socketPath); assert.deepEqual(f.calls[0].params, { title: "Ship", projectId: "p", workflowId: "w" }); await rejected(run(["sessions", "new", "--project", "p", "--workflow", "w"], "/missing"), /Session title/); });
test("legacy 05 room listing keeps session/status filters", async (context) => { const f = await fixture(context, () => ({ items: [] })); await run(["ls", "rooms", "--session", "s", "--status", "attention"], f.socketPath); assert.equal(f.calls[0].method, "rooms.list"); assert.equal(f.calls[0].params.sessionId, "s"); assert.equal(f.calls[0].params.status, "attention"); });
test("legacy 06 doctor negative remains exit one", async (context) => { const f = await fixture(context, () => ({ ok: false })); await assert.rejects(run(["doctor"], f.socketPath), (error) => error.code === 1); });
test("legacy 07 help documents legacy and global options", async () => { const { stdout } = await exec(cli, ["help"]); for (const fragment of ["dovsky doctor", "--session ID", "--new-room", "dovsky sessions", "[--project ID]", "--socket PATH"]) assert.match(stdout, new RegExp(fragment.replace(/[|()[\]{}+*?.\\^$]/g, "\\$&"))); });
test("legacy 08 control prints delivery notice", async (context) => { const f = await fixture(context); const { stderr } = await exec(cli, ["control", "t", "decision", "go", "--socket", f.socketPath]); assert.equal(f.calls[0].method, "tasks.controls.create"); assert.match(stderr, /delivery and acknowledgement are separate/i); });
test("legacy 09 wait-task keeps noncompleted negative", async (context) => { const f = await fixture(context, () => ({ task: { state: "blocked" } })); await assert.rejects(run(["wait-task", "t"], f.socketPath), (error) => error.code === 1); });
test("legacy 10 task control RPCs remain separate", async (context) => { const f = await fixture(context); await run(["checkpoint", "t", "--job", "j"], f.socketPath); await run(["ack", "t", "c1", "c2", "--job", "j"], f.socketPath); assert.equal(f.calls[0].method, "tasks.checkpoint"); assert.deepEqual(f.calls[1].params.controlIds, ["c1", "c2"]); });
test("legacy 11 resume binds reviewed worktree and fingerprint", async (context) => { const f = await fixture(context); const fingerprint = "a".repeat(64); await run(["resume", "t", "--cwd", "../candidate", "--expected-fingerprint", fingerprint], f.socketPath); assert.equal(f.calls[0].params.expectedFingerprint, fingerprint); await rejected(run(["resume", "t", "--cwd", "x"], "/missing"), /Missing required/); });
test("legacy 12 events contract intentionally defaults to peek", async (context) => { const f = await fixture(context, () => ({ items: [] })); await run(["events", "operator", "--limit", "10"], f.socketPath); assert.equal(f.calls[0].method, "events.peek"); assert.equal("idempotencyKey" in f.calls[0], false); await run(["events", "take", "operator"], f.socketPath); assert.equal(f.calls[1].method, "events.consume"); });
test("legacy 13 event ack and drain mutations retain envelopes", async (context) => { const f = await fixture(context); await run(["events-ack", "operator", "--through", "42"], f.socketPath); await run(["drain", "on"], f.socketPath); assert.equal(f.calls[0].params.throughId, 42); assert.equal(f.calls[1].params.enabled, true); });
test("legacy 14 release operation has only semantic operation ID", async (context) => { const f = await fixture(context, () => ({ state: "reconcile_required" })); await run(["operation", "execute", "o"], f.socketPath); assert.equal(f.calls[0].method, "releases.operations.execute"); assert.deepEqual(f.calls[0].params, { operationId: "o" }); });
test("legacy 15 authorization input remains exact JSON", async (context) => { const f = await fixture(context); const file = path.join(f.root, "input.json"), input = { taskId: "t", actions: ["push"], source: { actor: "human" } }; await writeFile(file, JSON.stringify(input)); await run(["authorization", "grant", "--file", file], f.socketPath); assert.deepEqual(f.calls[0].params, input); });
test("legacy 16 every mutation forwards bounded inherited depth", async (context) => { const f = await fixture(context); await run(["checkpoint", "t", "--job", "j"], f.socketPath, { env: { ...process.env, DOVSKY_DEPTH: "2" } }); assert.equal(f.calls[0].params.depth, 2); await rejected(run(["checkpoint", "t", "--job", "j"], "/missing", { env: { ...process.env, DOVSKY_DEPTH: "nope" } }), /DOVSKY_DEPTH/); });
test("legacy 17 acceptance check cannot confuse success and acceptance", async (context) => { const f = await fixture(context, () => ({ accepted: false, problems: ["human"] })); await assert.rejects(run(["acceptance-check", "j"], f.socketPath), (error) => error.code === 1); });
test("legacy 18 send forwards evaluation acceptance file", async (context) => { const f = await fixture(context), file = path.join(f.root, "acceptance.json"); await writeFile(file, JSON.stringify({ criteria: ["known"] })); await run(["send", "x", "--project", "p", "--workflow", "w", "--to", "codex", "--eval", "medium", "--acceptance-file", file], f.socketPath); assert.equal(f.calls[0].params.evalLevel, "medium"); assert.deepEqual(f.calls[0].params.acceptance.criteria, ["known"]); });
test("legacy 19 stdin supplies turn body", async (context) => { const f = await fixture(context), file = path.join(f.root, "body"); await writeFile(file, "stdin body"); await exec("sh", ["-c", `${JSON.stringify(cli)} record --author human --title T --project p --workflow w --socket ${JSON.stringify(f.socketPath)} --json < ${JSON.stringify(file)}`]); assert.equal(f.calls[0].params.body, "stdin body"); });
test("legacy 20 review flags preserve other and none", async (context) => { const f = await fixture(context); await run(["send", "x", "--project", "p", "--workflow", "w", "--review"], f.socketPath); assert.equal(f.calls[0].params.review, "other"); await run(["send", "x", "--project", "p", "--workflow", "w", "--no-review"], f.socketPath); assert.equal(f.calls[1].params.review, "none"); });
test("legacy 21 grade intentionally omits caller-controlled source", async (context) => { const f = await fixture(context); await run(["grade", "j", "good"], f.socketPath); assert.equal(f.calls[0].method, "jobs.grade"); assert.equal("source" in f.calls[0].params, false); });
test("legacy 22 review provider/tier remain narrow", async (context) => { const f = await fixture(context); await run(["review", "j", "--to", "codex", "--tier", "hard"], f.socketPath); assert.deepEqual(f.calls[0].params, { jobId: "j", provider: "codex", tier: "hard" }); });
test("legacy 23 JSON output strips terminal controls", async (context) => { const f = await fixture(context, () => ({ state: "succeeded", gradeNote: "\x1b[2Jbad" })); const { stdout } = await run(["wait", "j"], f.socketPath); assert.equal(JSON.parse(stdout).gradeNote, "bad"); });
test("legacy 24 status restores sanitized review reasons and queue wait", async (context) => { const f = await fixture(context, () => ({ room: { id: "r", title: "T" }, jobs: [{ id: "job-12345678", provider: "codex", state: "succeeded", role: "work", gradeNote: "\x1b[2Jbad", usage: { queueWaitMs: 0 }, review: { verdict: "refuted", provider: "claude", round: 1 } }] })); const { stdout } = await exec(cli, ["status", "r", "--socket", f.socketPath]); assert.match(stdout, /reasons: bad/); assert.match(stdout, /queue wait: 0ms/); });
test("legacy 25 daemon error code and message are sanitized", async (context) => { const f = await fixture(context, () => ({ __rpc: true, value: { ok: false, error: { code: "BAD\x1b[2J", message: "\x1b[31mBad thing" } } })); await assert.rejects(exec(cli, ["doctor", "--socket", f.socketPath]), (error) => /dovsky: BAD: Bad thing/.test(error.stderr)); });
test("legacy 26 C1 terminal controls remain stripped", async (context) => { const f = await fixture(context, () => ({ state: "succeeded", gradeNote: "bad\x9b2Jtext" })); const { stdout } = await run(["wait", "j"], f.socketPath); assert.equal(JSON.parse(stdout).gradeNote, "badtext"); });
test("legacy 27 from-review chooses newest and rejects prompt", async (context) => { const f = await fixture(context, (request) => request.method === "rooms.get" ? { jobs: [{ role: "work", provider: "claude", createdAt: "2026-01-02", gradeNote: "NEW", review: { verdict: "refuted" } }, { role: "work", provider: "codex", createdAt: "2026-01-01", gradeNote: "OLD", review: { verdict: "refuted" } }] } : {}); await run(["followup", "r", "--from-review"], f.socketPath); assert.match(f.calls[1].params.body, /NEW/); await rejected(run(["followup", "r", "extra", "--from-review"], "/missing"), /does not accept/); });
test("legacy 28 acceptance echoes never permit stale explicit values", async (context) => { const f = await fixture(context, () => ({ accepted: false, evaluation: { criteria: [], fingerprint: "f", evidenceHash: "e" } })); await rejected(run(["reject", "j", "--note", "no", "--fingerprint", "wrong"], f.socketPath), /must match/); await rejected(run(["accept", "j", "--note", "yes", "--evidence-hash", "wrong"], f.socketPath), /must match/); assert.equal(f.calls.length, 2); });

test("new evidence pagination, diff and output use local artifact pages", async (context) => { const f = await fixture(context, (request) => { if (request.method === "jobs.get") return { roomId: "r" }; if (request.method === "jobs.evidence") return request.params.cursor ? { artifacts: [{ id: "a", kind: "evidence" }], changes: [{ path: "b", additions: 2, deletions: 1 }], nextCursor: null } : { changes: [{ path: "a", additions: 1, deletions: 0 }], nextCursor: "next" }; if (request.method === "artifacts.read") return { data: Buffer.from("proof").toString("base64"), nextOffset: null }; return {}; }); const out = path.join(f.root, "proof.md"); await run(["evidence", "j", "--out", out], f.socketPath); assert.equal(await readFile(out, "utf8"), "proof"); await run(["diff", "j", "--stat"], f.socketPath); assert.ok(f.calls.some((call) => call.method === "artifacts.read")); });
test("new import, PR, routing and rollout commands use planned local RPCs", async (context) => { const f = await fixture(context, (request) => request.method === "jobs.acceptance.check" ? { accepted: true, evaluation: { fingerprint: "f", evidenceHash: "e" } } : request.method === "github.pr.status" ? { state: "merged" } : {}); const spool = path.join(f.root, "spool"); await (await import("node:fs/promises")).mkdir(spool); await run(["import-legacy", "--source", spool], f.socketPath); await run(["import-legacy", "--source", spool, "--apply"], f.socketPath); await run(["pr", "j"], f.socketPath); await run(["pr", "status", "j"], f.socketPath); await run(["routing", "unpin", "--provider", "codex", "--workflow", "w"], f.socketPath); await run(["rollouts", "j"], f.socketPath); assert.ok(f.calls.some((call) => call.method === "legacy.import" && call.idempotencyKey.startsWith("legacy:"))); assert.ok(f.calls.some((call) => call.method === "github.pr.create" && call.idempotencyKey === "pr:j")); assert.ok(f.calls.some((call) => call.method === "routing.unpin")); assert.ok(f.calls.some((call) => call.method === "rollouts.get")); });
test("new bounded flags reject bare or malformed values", async (context) => { const f = await fixture(context); await rejected(run(["send", "x", "--project", "p", "--workflow", "w", "--rollouts"], f.socketPath), /Missing required --rollouts/); await rejected(run(["execution", "reconcile", "j", "--expect", "nope"], f.socketPath), /--expect/); });
