import { readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";

/** Frozen schema captured from fc5a020, never generated by the current migrator. */
export function historicalDatabase(path: string): DatabaseSync {
  const db = new DatabaseSync(path);
  db.exec(readFileSync(new URL("../../src/__fixtures__/schema-v13.sql", import.meta.url), "utf8"));
  return db;
}

export function seedHistoricalDatabase(path: string): void {
  const db = historicalDatabase(path);
  try {
    db.exec("BEGIN; PRAGMA defer_foreign_keys=ON;");
    db.exec(`
      INSERT INTO sessions VALUES('session','Session','project','review',1,'2026-09-09','2026-09-09');
      INSERT INTO rooms(id,title,project_id,workflow_id,created_at,updated_at,session_id)
        VALUES('room','Preserved room','project','review','2026-09-09','2026-09-09','session');
    `);
    for (const [id, predecessor, prompt, state] of [
      ['parent', null, 'old prompt', 'running'], ['child', 'parent', 'continue', 'queued'], ['grandchild', 'child', 'continue again', 'queued'],
    ] as const) {
      db.prepare(`INSERT INTO jobs(id,room_id,project_id,workflow_id,provider,prompt,state,model,requested_model,
        predecessor_job_id,predecessor_pending,task_id,created_at,updated_at)
        VALUES(?,'room','project','review','codex',?,?,'gpt-5.6-terra','gpt-5.6-terra',?,?,'parent','2026-09-09','2026-09-09')`)
        .run(id, prompt, state, predecessor, predecessor ? 1 : 0);
      db.prepare(`INSERT INTO turns(id,job_id,room_id,author,recipient,body,created_at,status)
        VALUES(?,?,'room','human','codex',?,'2026-09-09','pending')`).run(`turn-${id}`,id,prompt);
    }
    db.exec(`
      INSERT INTO tasks(id,room_id,provider,latest_job_id,state,phase,created_at,updated_at)
        VALUES('parent','room','codex','grandchild','running','working','2026-09-09','2026-09-09');
      INSERT INTO task_controls(id,task_id,sequence,kind,body,created_at) VALUES('control','parent',1,'instruction','preserve this','2026-09-09');
      INSERT INTO task_ownership VALUES('/owned/tree','parent');
      INSERT INTO event_consumers VALUES('consumer','room',1,2);
      INSERT INTO daemon_settings VALUES('draining','true');
      INSERT INTO release_operations(id,task_id,room_id,semantic_key,state,data_json)
        VALUES('operation','parent','room','semantic','reconcile_required','{"receipt":"preserve"}');
      INSERT INTO release_targets VALUES('frontend','operation','owner');
      INSERT INTO events(room_id,job_id,type,occurred_at,data_json) VALUES('room','parent','job.created','2026-09-09','{"unchanged":true}');
      COMMIT;
    `);
  } finally { db.close(); }
}

/** Real v9 shape obtained by removing only columns/tables introduced in 10–13. */
export function downgradeHistoricalDatabase(path: string, variant: "schema9" | "visibility10" | "coordination10"): void {
  const db = new DatabaseSync(path);
  try {
    db.exec("PRAGMA foreign_keys=OFF; DROP INDEX rooms_session_idx; ALTER TABLE rooms DROP COLUMN session_id; ALTER TABLE rooms DROP COLUMN archived; ALTER TABLE rooms DROP COLUMN pinned; DROP TABLE sessions; DROP TABLE execution_leases;");
    if (variant !== "coordination10") {
      for (const table of ["release_targets", "release_operations", "release_authorizations", "release_candidates", "task_controls", "task_ownership", "event_consumers", "daemon_settings", "tasks"]) db.exec(`DROP TABLE ${table}`);
      db.exec("DROP INDEX jobs_task_idx; ALTER TABLE jobs DROP COLUMN task_id; ALTER TABLE jobs DROP COLUMN predecessor_pending;");
    }
    if (variant !== "visibility10") db.exec("ALTER TABLE jobs DROP COLUMN requested_model; ALTER TABLE jobs DROP COLUMN reported_model;");
    if (variant === "schema9") db.exec("ALTER TABLE jobs DROP COLUMN predecessor_job_id;");
    db.exec(`PRAGMA user_version=${variant === "schema9" ? 9 : 10}`);
  } finally { db.close(); }
}
